name: Docker Image CI

on:
  push:
    branches:
      - docker
  workflow_dispatch:

jobs:
  build_image:
    name: Build Docker Image
    runs-on: ubuntu-latest
    steps:
    - name: checkout this repo
      uses: actions/checkout@v3
      with: 
        ref: 'docker'
    - name: login to docker hub
      uses: docker/login-action@v2.1.0
      with:
        username: distinctwind
        password: ${{secrets.DOCKER_ACCESS_TOKEN}}
    - name: add metadata for docker image
      id: meta
      uses: docker/metadata-action@v4.4.0
      with:
        images: distinctwind/visual-decaf
        tags:
          type=raw, value=latest
    - name: build and push docker images
      uses: docker/build-push-action@v4.0.0
      with:
        context: .
        file: ./DockerFile
        push: true
        tags: ${{steps.meta.outputs.tags}}
        labels: ${{steps.meta.outputs.labels}}
